pull_request_title: 'chore(i18n-crowdin): new crowdin translation'
commit_message: 'chore(i18n-crowdin): new translations for %original_file_name% (%language%)'

files:
  - source: /src/languages/en-US/**/*.json
    translation: /src/languages/%locale%/**/%original_file_name%
